#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cxxfilt
Version  : 0.1.0
Release  : 5
URL      : https://files.pythonhosted.org/packages/d1/7f/15a38ca80ce8cf46810413d863a1f67b97edcafca2df8e1eaa35fbeec975/cxxfilt-0.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/d1/7f/15a38ca80ce8cf46810413d863a1f67b97edcafca2df8e1eaa35fbeec975/cxxfilt-0.1.0.tar.gz
Summary  : Python interface to c++filt / abi::__cxa_demangle
Group    : Development/Tools
License  : BSD-3-Clause
Requires: cxxfilt-python3
Requires: cxxfilt-python
BuildRequires : pbr
BuildRequires : pip

BuildRequires : python3-dev
BuildRequires : setuptools

%description
=======

%package python
Summary: python components for the cxxfilt package.
Group: Default
Requires: cxxfilt-python3

%description python
python components for the cxxfilt package.


%package python3
Summary: python3 components for the cxxfilt package.
Group: Default
Requires: python3-core

%description python3
python3 components for the cxxfilt package.


%prep
%setup -q -n cxxfilt-0.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1528564853
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
